services:
  mqtt_broker:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  server:
    build:
      context: ../server
    container_name: server
    depends_on:
      - mqtt_broker
    environment:
      - ROLE=server               # Specifies the role as "server"
      - BROKER=mosquitto          # Name of the MQTT broker

  iot_node:
    build:
      context: ../iot_nodes
    depends_on:
      - mqtt_broker
    environment:
      - ROLE=node                 # Specifies the role as "node"
      - BROKER=mosquitto          # Name of the MQTT broker
